version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.5.4
    working_directory: ~/root

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum ".circleci/requirements.txt" }}
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r .circleci/requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum ".circleci/requirements.txt" }}

      - run:
          name: run tests
          command: |
            python RunTests.py

      - store_artifacts:
          path: Logs
          destination: Logs
      - store_artifacts:
          path: TestOutputs
          destination: MetaData
